---

- name: import escapace.aws_cli role
  ansible.builtin.import_role:
    name: escapace.aws_cli

- name: import escapace.aws_environment role
  ansible.builtin.import_role:
    name: escapace.aws_environment

- name: create tailscale directories
  ansible.builtin.file:
    owner: root
    group: root
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items:
    - "/opt/tailscale"
    - "/opt/tailscale/bin"

- name: copy tailscale-up script
  ansible.builtin.copy:
    src: tailscale-up
    dest: /opt/tailscale/bin/tailscale-up
    mode: '0750'
    owner: root
    group: root
  tags:
    - run-tailscale

- name: copy run-tailscale script
  ansible.builtin.copy:
    src: run-tailscale
    dest: /opt/tailscale/bin/run-tailscale
    mode: '0750'
    owner: root
    group: root
  tags:
    - run-tailscale
