---

- name: install dependencies
  dnf:
    name: "{{ packages }}"
    state: present
    allowerasing: true

  vars:
    packages:
      - dnf-plugins-core
      - curl
      - jq

- name: install tailscale repos
  template:
    src: tailscale.repo.j2
    dest: /etc/yum.repos.d/tailscale.repo
    mode: 0644

- name: install tailscale
  dnf:
    name: tailscale
    state: present

- name: create directory for systemd drop-ins
  file:
    path: /etc/systemd/system/tailscaled.service.d
    owner: root
    group: root
    state: directory
    mode: 0755
  notify:
    - tailscale daemon-reload

- name: systemd drop-in for options
  template:
    src:  "tailscale-service-ferm.conf.j2"
    dest: "/etc/systemd/system/tailscaled.service.d/010-ferm.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - tailscale daemon-reload

- name: enable tailscaled on boot
  service: name=tailscaled enabled=yes
  when: not tailscale_role_debug|bool

- name: create the tailscale ferm conf files
  template: src=templates/ferm-tailscale.conf.j2 dest=/etc/ferm/ferm.d/1020-tailscale.conf owner=root group=root mode=0600

- name: create the tailscale ferm var files
  template: src=templates/ferm-tailscale-variables.conf.j2 dest=/etc/ferm/vars.d/1010-tailscale.conf owner=root group=root mode=0600

- include_tasks: provider-ec2.yml
  when: provider is defined and provider == "ec2"

# - name: check if kresd.conf.d exists
#   ansible.builtin.stat:
#     path: /etc/knot-resolver/kresd.conf.d/
#   register: tailscale_kresd_conf_d
#   changed_when: false
#
# - name: tailscale kresd configuration
#   template:
#     src: "kresd-view-tailscale.conf.j2"
#     dest: "/etc/knot-resolver/kresd.conf.d/910-view-tailscale.conf"
#     owner: root
#     group: knot-resolver
#     mode: 0640
#   when: tailscale_kresd_conf_d.stat.isdir is defined and tailscale_kresd_conf_d.stat.isdir
